<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2012 (http://www.altova.com) by rrubei (Sogei S.p.A.) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cm="urn:www.agenziaentrate.gov.it:specificheTecniche:common:v2" xmlns="urn:www.agenziaentrate.gov.it:specificheTecniche:sco:common:v3" targetNamespace="urn:www.agenziaentrate.gov.it:specificheTecniche:sco:common:v3" elementFormDefault="qualified" attributeFormDefault="unqualified" version="4.0">
	<xs:annotation>
		<xs:documentation xml:lang="it"><![CDATA[
		Versione 4.0 - 12/07/13
		- modificato targetNamespace typesDati_v3.xsd typesFiscali_v4.xsd e tutti i Type Associati

		Versione 3.0 - 15/02/13
		- modificato targetNamespace

		Versione 2.0 - 15/02/12
		- modificato namespace associato al prefisso cm e targetNamespace
		- introdotto complexType Firma_Type
		- modificato complexType Tipo_Dichiarazione_Type introducendo element IntegrativaArt2Co8Ter
		- modificato tipo dati associato agli elementi Telefono e Fax contenuti all'interno dei complexTypes SoggettoFiscale e DatiSottoscrittore
		- modificato tipo dati associato all'elemento Cap contenuto all'interno dei complexTypes Domicilio_Ita_Type e Domicilio_EE_Type
		]]></xs:documentation>
	</xs:annotation>
	<xs:import namespace="urn:www.agenziaentrate.gov.it:specificheTecniche:common:v2" schemaLocation="typesDati_v3.xsd"/>
	<xs:import namespace="urn:www.agenziaentrate.gov.it:specificheTecniche:common:v2" schemaLocation="typesProvincie_v2.xsd"/>
	<xs:include schemaLocation="typesFiscali_v4.xsd"/>
	<xs:include schemaLocation="typeEventi_v3.xsd"/>
	<xs:complexType name="Frontespizio_Type">
		<xs:sequence>
			<xs:element name="SoggettoFiscale" type="Soggetto_Fiscale_Type"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Soggetto_Fiscale_Type">
		<xs:sequence>
			<xs:element name="CodiceFiscale" type="cm:DatoCfType"/>
			<xs:element name="Email" type="cm:DatoEmType" minOccurs="0"/>
			<xs:element name="Telefono" type="cm:DatoTlType" minOccurs="0"/>
			<xs:element name="Fax" type="cm:DatoTlType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Soggetti_Diversi_Da_PF_Type">
		<xs:sequence>
			<xs:element name="Denominazione" type="cm:DatoAnType"/>
			<xs:element name="SedeLegale" type="Domicilio_EE_Type"/>
			<xs:element name="DomicilioFiscale" type="Domicilio_Fiscale_Type" minOccurs="0"/>
			<xs:element name="DataApprovazioneBilancio" type="cm:DatoDtType" minOccurs="0"/>
			<xs:element name="TermineApprovazioneBilancio" type="cm:DatoDtType" minOccurs="0"/>
			<xs:element name="InizioPeriodoImposta" type="cm:DatoDtType"/>
			<xs:element name="FinePeriodoImposta" type="cm:DatoDtType"/>
			<xs:element name="Stato" type="Stato_Type"/>
			<xs:element name="NaturaGiuridica" type="Natura_Giuridica_Type"/>
			<xs:element name="Situazione" type="Situazione_Type"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Domicilio_Fiscale_Type">
		<xs:complexContent>
			<xs:extension base="Domicilio_Ita_Type">
				<xs:sequence>
					<xs:element name="DataVariazione" type="cm:DatoD6Type" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Soggetti_Non_Residenti_Type">
		<xs:sequence>
			<xs:element name="StatoEsteroResidenza" type="cm:DatoAnType" minOccurs="0"/>
			<xs:element name="CodiceStatoEstero" type="cm:DatoAnType" minOccurs="0"/>
			<xs:element name="CodiceIdentificazioneEstero" type="cm:DatoAnType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Persone_Fisiche_Type">
		<xs:sequence>
			<xs:element name="DatiAnagrafici" type="Dati_Anagrafici_Type"/>
			<xs:element name="ResidenzaAnagrafica" type="Residenza_Anagrafica_Type"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Dati_Anagrafici_Type">
		<xs:sequence>
			<xs:element name="Cognome" type="cm:DatoAnType"/>
			<xs:element name="Nome" type="cm:DatoAnType"/>
			<xs:element name="Sesso" type="Sesso_Type"/>
			<xs:element name="DataNascita" type="cm:DatoDtType"/>
			<xs:element name="ComuneNascita" type="cm:DatoAnType"/>
			<xs:element name="ProvinciaNascita" type="cm:PN_Type" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Residenza_Anagrafica_Type">
		<xs:complexContent>
			<xs:extension base="Domicilio_Ita_Type">
				<xs:sequence>
					<xs:element name="DataVariazione" type="cm:DatoDtType" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Domicilio_Ita_Type">
		<xs:sequence>
			<xs:element name="Comune" type="cm:DatoAnType"/>
			<xs:element name="Provincia" type="cm:PR_Type"/>
			<xs:element name="CodiceComune" type="cm:DatoAnType"/>
			<xs:element name="Indirizzo" type="cm:DatoAnType"/>
			<xs:element name="Cap" type="cm:DatoCpType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Domicilio_EE_Type">
		<xs:sequence>
			<xs:element name="Comune" type="cm:DatoAnType"/>
			<xs:element name="Provincia" type="cm:PE_Type" minOccurs="0"/>
			<xs:element name="CodiceComune" type="cm:DatoAnType" minOccurs="0"/>
			<xs:element name="Indirizzo" type="cm:DatoAnType" minOccurs="0"/>
			<xs:element name="Cap" type="cm:DatoCpType" minOccurs="0"/>
			<xs:element name="DataVariazione" type="cm:DatoD6Type" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Dati_Sottoscrittore_Type">
		<xs:sequence>
			<xs:element name="CodiceFiscale" type="cm:DatoCfType"/>
			<xs:element name="CodiceCarica" type="Codice_Carica_Type"/>
			<xs:element name="CodiceFiscaleSocieta" type="cm:DatoCnType" minOccurs="0"/>
			<xs:element name="DatiAnagrafici" type="Dati_Anagrafici_Type"/>
			<xs:element name="ResidenzaEstera" type="Residenza_Estera_Type" minOccurs="0"/>
			<xs:element name="Telefono" type="cm:DatoTlType" minOccurs="0"/>
			<xs:element name="DataCarica" type="cm:DatoDtType" minOccurs="0"/>
			<xs:element name="InizioProcedura" type="cm:DatoDtType" minOccurs="0"/>
			<xs:element name="ProceduraNonTerminata" type="cm:DatoCbType" minOccurs="0"/>
			<xs:element name="FineProcedura" type="cm:DatoDtType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Impegno_A_Trasmettere_Type">
		<xs:sequence>
			<xs:element name="CFintermediario" type="cm:DatoCfType"/>
			<xs:element name="NumeroIscrAlboCAF" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="cm:DatoAnType">
						<xs:maxLength value="5"/>
						<xs:pattern value="[0-9]{5}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ImpegnoATrasmettere">
				<xs:simpleType>
					<xs:restriction base="cm:DatoNpType">
						<xs:pattern value="1|2"/>
						<xs:enumeration value="1"/>
						<xs:enumeration value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="RicezioneAvvisoTelem" type="cm:DatoCbType" minOccurs="0"/>
			<xs:element name="DataImpegno" type="cm:DatoDtType"/>
			<xs:element name="FirmaIntermediario" type="cm:DatoCbType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Visto_Conformita_Type">
		<xs:sequence>
			<xs:choice>
				<xs:element name="VistoCAF">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CFResp" type="cm:DatoCfType"/>
							<xs:element name="CF_CAF" type="cm:DatoCnType"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="CFprofessionista" type="cm:DatoCfType"/>
			</xs:choice>
			<xs:element name="Firma" type="cm:DatoCbType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Firma_Revisore_Type">
		<xs:sequence>
			<xs:element name="Soggetto" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="cm:DatoNpType">
						<xs:pattern value="[1-4]"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="CodiceFiscale" type="cm:DatoCfType" minOccurs="0"/>
			<xs:element name="FirmaDichiarante" type="cm:DatoCbType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Tipo_Dichiarazione_Type">
		<xs:choice>
			<xs:element name="Correttiva" type="cm:DatoCbType"/>
			<xs:element name="IntegrativaAFavore" type="cm:DatoCbType"/>
			<xs:element name="Integrativa" type="cm:DatoCbType"/>
			<xs:element name="IntegrativaArt2Co8Ter" type="cm:DatoCbType"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="Residenza_Estera_Type">
		<xs:sequence>
			<xs:element name="CodiceStatoEstero">
				<xs:simpleType>
					<xs:restriction base="cm:DatoAnType">
						<xs:length value="3"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="StatoFederato" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="cm:DatoAnType">
						<xs:maxLength value="24"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="LocalitaEstero" type="cm:DatoAnType" minOccurs="0"/>
			<xs:element name="IndirizzoEstero" type="cm:DatoAnType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Firma_Type">
		<xs:sequence>
			<xs:element name="Firma" type="cm:DatoCbType" minOccurs="0"/>
			<xs:element name="CodiceFiscale" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="([0-9A-Z\-]|&quot;){0,1}([0-9A-Z&amp;]|'|\-|\.|,|\s|/|°|\^|\(|\)|À|È|É|Ì|Ò|Ù|Ü|&quot;|\\|\||\+)*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>
